"""
config.py
=========
Centralized project settings. Imported by app.py, fetch_wars.py, wars_gantt.py.
"""

from datetime import datetime

# ── General ──────────────────────────────────────────────────────────────────
CURRENT_YEAR = datetime.now().year
CSV_FILE = "wars.csv"

# ── Wikipedia scraper (fetch_wars) ───────────────────────────────────────────
BASE_URL = "https://en.wikipedia.org"
HEADERS = {"User-Agent": "WarsTimelineBot/1.0 (educational project)"}

LIST_PAGES = [
    "/wiki/List_of_wars:_1900%E2%80%931944",
    "/wiki/List_of_wars:_1945%E2%80%931989",
    "/wiki/List_of_wars:_1990%E2%80%932002",
    "/wiki/List_of_wars:_2003%E2%80%93present",
]

# ── Region classification (wars_gantt) ───────────────────────────────────────
REGION_COLORS = {
    "Europe":      "#e05252",
    "Middle East": "#e08844",
    "Asia":        "#d4b445",
    "Africa":      "#7ab648",
    "Americas":    "#4a9fd4",
    "Pacific":     "#7b6fd4",
    "Global":      "#c45abf",
    "Other":       "#8a8a8a",
}

REGION_KEYWORDS = {
    "Europe":      ["europe","european","balkan","greek","greece","yugoslav",
                    "russian","russia","ukrainian","ukrain","polish","poland",
                    "german","germany","french","france","spain","spanish",
                    "italian","italy","british","britain","irish","ireland",
                    "finnish","finland","hungarian","hungary","romanian","romania",
                    "bulgarian","bulgaria","serbian","serbia","croatian","croatia",
                    "bosnian","bosnia","czech","slovak","austria","dutch",
                    "netherlands","belgian","belgium","swedish","norway",
                    "norwegian","danish","denmark","swiss","portugal","portuguese",
                    "albanian","albania","macedon","montenegr","moldov",
                    "baltic","latvian","lithuanian","estonian","chechen",
                    "chechnya","kosovo","crimea","cyprus","troubles",
                    # Added: uprisings & revolts with European locations
                    "silesian","spartacist","kapp putsch","ruhr",
                    "transnistria","ossetia","georgian civil",
                    "abkhazia","ingushetia","north caucasus",
                    "dagestan","kronstadt","łódź","cattaro",
                    "carinthia","noemvriana","toplica",
                    "kornilov","october revolution","february revolution",
                    "july days","left sr uprising",
                    "easter rising","corfu","impresa di fiume",
                    "singing revolution","reggio revolt",
                    "preševo","goryani","plzeň","kengir",
                    "leonardopoulos","theriso","maritz rebellion",
                    "rand rebellion","judenburg","radomir",
                    "vienna","tatarbunary","sanjurjada",
                    "july putsch","asturian",
                    "february 26 incident","legionnaires' rebellion",
                    "continuation war","lapland war","winter war",
                    "corsican",
                    # Added round 2
                    "holy apostles monastery","ilinden","preobrazhenie",
                    "vlora","albona","georgian coup","georgia",
                    "red army invasion of georgia","march action",
                    "hamburg uprising","beer hall putsch","klaipėda",
                    "september uprising","zazejskie","incident at petrich",
                    "casas viejas","narrenrevolte","scythe cross",
                    "czortków","herzegovina","poznań","basque",
                    "ten-day war","soviet coup","east prigorodny",
                    "banat","pechenga","aunus","ingrian",
                    "sochi conflict","black sea mutiny","sejny",
                    "khotyn","maquis","lesko","kolašin",
                    "tikveš","ohrid","debar"],
    "Middle East": ["arab","iraq","iran","persian","israel","israeli","lebanese",
                    "lebanon","syrian","syria","yemeni","yemen","gulf","ottoman",
                    "turkey","turkish","afghan","afghanistan","kurd","kurdish",
                    "palestinian","palesti","hezbollah","houthi","bahrain",
                    "qatar","saudi","jordan","oman","emirat",
                    # Added: revolts, tribes, and places
                    "hamawand","shoubak","sharjah","kuwaiti","rashidi",
                    "wazir","mahsud","kabul","khel","khost",
                    "barzani","barzanji","mosul","dersim","bitlis",
                    "panjshir","dhofar","intifada","al-khurma",
                    "mesopotamia","euphrates","nejd","al-hasa",
                    "ikhwan","najran","asir","zaraniq","muscat",
                    "al-jawf","rijal al-ma","mutair","buraida",
                    "sistan","baluchestan","balochistan","khuzestan",
                    "herat","poonch","pashtun","kandahar",
                    "mohmand","tochi","waziristan","bajaur",
                    "grand mosque","qatif","shebaa",
                    "gafsa","sinai","heglig","kufra",
                    "saur revolution","nojeh","simko",
                    "salar-al-daulah","khorosan","qin-lian",
                    "al-wadiah","al-ansar","paquisha",
                    "urtatagai","bizerte",
                    # Added round 2
                    "young turk","hauran druze","al-bejat",
                    "karak revolt","alawite","jabal al-gharbi",
                    "sheikh khazal","sheikh said","alizai",
                    "adwan","beytüşşebab","sason","ararat",
                    "botan","katawz","hama rashid",
                    "aden","jebel akhdar","upper yafa",
                    "14 july revolution","ramadan revolution",
                    "ar-rashid","sand war","black september",
                    "abu musa","buraimi","war of attrition",
                    "gaza","puk insurgency","kdpi",
                    "hazara","goharshad","yazidi",
                    "nestorian","barzan","kuhistan",
                    "taliban","khyber pakhtunkhwa",
                    "amol uprising","diyarbakır",
                    "battle of kanzaan","battle of jarrab",
                    "senussi","zaian","malabar",
                    "punjab rebellion","anti-foreign revolt",
                    "taba crisis","1906 mesopotamia",
                    "armenian–azerbaijani","kargil",
                    "fatah–hamas","islamic state",
                    "russo-georgian","conquest of ha'il",
                    "operation scorched earth",
                    "battle of al jawf"],
    "Asia":        ["china","chinese","korean","korea","vietnam","vietnamese",
                    "india","indian","pakistan","burm","myanmar","cambodia",
                    "cambodian","laos","laotian","thailand","thai","indonesia",
                    "indonesian","malay","philippine","filipino","sino",
                    "japan","japanese","tibet","tibetan","taiwan","formosa",
                    "bangladesh","bengal","nepal","sri lank","ceylon",
                    "kashmir","xinjiang","uyghur","khmer","hmong","moro",
                    "boxer rebellion","taiping","sikh","assam","manipur",
                    "naxal","tamil",
                    # Added: Indonesian islands, Chinese uprisings, Indian revolts
                    "java","jambi","merauke","sulawesi","sumba",
                    "sumbawa","lombok","flores","solor","tidore",
                    "yapen","kerinci","minangkabau","mentawei",
                    "kalimantan","batang","indragiri","langkat",
                    "belitung","toba","batak","nias",
                    "moluc","maluku","aceh",
                    "xinhai","anqing","huanggang","huizhou",
                    "qinzhou","zhennanguan","hekou","mapaoying",
                    "ping-liu-li","great ming","gengxu",
                    "northern expedition","bai lang",
                    "guangdong","guangxi","beipu","musha",
                    "truku","chamdo","kuomintang",
                    "eelam","telangana","hyderabad","junagadh",
                    "nagaland","chittagong","rampa rebellion",
                    "punnapra","vayalar","nathu la","cho la",
                    "siachen","sumdorong","rakhine","marawi",
                    "darul islam","makassar","sarawak",
                    "hukbalahap","jesselton","lahad datu",
                    "zamboanga","mindanao","brunei revolt",
                    "ngệ","quỳnh","thái nguyên",
                    "yên bái","annam","fulro",
                    "bastar","jvp insurrection","gwangju",
                    "kyrgyz","tajikist","batken",
                    "gorno-badakhshan","mongol",
                    "kumul","ngolok","tugsbuyant",
                    "polubotkivtsi","operation trikora",
                    "saya san","spirit soldier",
                    # Added round 2
                    "bantin","ngiao","korintji","dayak",
                    "gajo","alas islands","onin",
                    "toli-toli","garut","north java",
                    "blayong","tapani","kelantan","rundum",
                    "singapore mutiny","kalat",
                    "manchu restoration","constitutional protection",
                    "zhili","fengtian","chiang-gui",
                    "central plains war","two-liu war",
                    "second guangzhou","second revolution",
                    "xiong mi chang","anti-fengtian",
                    "tarimese","central asian revolt",
                    "1934 khamba","boworadet",
                    "ili rebellion","august revolution",
                    "madiun","yeosu","suncheon","jeju",
                    "prri","permesta","rebellion of the pilots",
                    "annexation of goa","annexation of dadra",
                    "30 september","paracel islands",
                    "de zeven provinciën",
                    "january 28 incident","flour revolt",
                    "battle of marrakech","afridi",
                    "crazy fakir","oromo","pgrs/paraku",
                    "maldives coup","1990 mindanao",
                    "iraqi","haji abdul rahman",
                    "kirghiz","kazakh","kazym",
                    "basmachi","bukhara","alakat",
                    "khorinskoe","muromtsevsky","tungus",
                    "arube uprising","ndf rebellion",
                    "surinamese","cabinda",
                    "rebellion of the lost","shaba"],
    "Africa":      ["africa","african","ethiopia","ethiopian","somali","somalia",
                    "sudan","sudanese","congo","congolese","angola","angolan",
                    "mozambi","rwanda","rwandan","liberia","liberian",
                    "sierra leone","nigeria","nigerian","egypt","egyptian",
                    "algeri","libya","libyan","kenya","kenyan","zimbabwe",
                    "uganda","ugandan","chad","chadian","mali","malian",
                    "eritrea","eritrean","burundi","cameroon","central african",
                    "ivory coast","ghana","senegal","niger ","namibia",
                    "south africa","morocco","moroccan","tunisia","tunisian",
                    "darfur","sahara","sahel","mau mau","biafra","boko haram",
                    "hutu","tutsi","zulu","boer","rhodesia","madagascar",
                    "mozambique",
                    # Added: tribal names, local places, colonial wars
                    "golden stool","zande","agar dinka","atwot dinka",
                    "bastaard","mapondera","anglo-aro","herero",
                    "nama uprising","bondelswarts","kavango",
                    "ondonga","uukwambi","uukwanyama","ovambo",
                    "rehoboth","sokoto","bambatha","dembos",
                    "maji maji","mahafaly","kru coast",
                    "kaocen","adubi","woyane",
                    "kongo revolt","kongo-wara","zanzibar",
                    "simba rebellion","katanga","stanleyville",
                    "luluabourg","jadotville","masisi",
                    "ituri","kivu","m23","pool war",
                    "kamwina nsapu","kasese","anglophone crisis",
                    "cabo delgado","casamance","bamileke",
                    "tuareg","shifta","bale revolt",
                    "guinea-bissau","ogaden","dongo",
                    "linda nchi","abyan","baragoi",
                    "ndogboyosoi","entumbane","gambian",
                    "ciskei","transkei","aswan tribal",
                    "benishangul","oromia","ola insurgency",
                    "oyango dande","kolongongo",
                    "sadiavahe","bussa rebellion",
                    "somba rebellion","volta-bani",
                    "kordofan","tegale","habuba",
                    "anjouan","operation astute",
                    "bakassi","djibouti","wadai",
                    "ifni","rif war","mossi",
                    "malagasy","renamo","cape nguni",
                    # Added round 2
                    "kuanhama","bailundo","namas in maltahöhe",
                    "1904 nama","sirte","misurata","warfala",
                    "battle of segale","1927 nuer",
                    "antananarivo","women's war",
                    "gugsa wale","annexation of jimma",
                    "inamujandi","dieu python",
                    "1943 barzani revolt","palm sunday coup",
                    "safi rebellion","1998 monrovia",
                    "batwa","luba","second ivorian",
                    "first ivorian","mount elgon",
                    "agacher","bophuthatswana",
                    "second afar","adf insurgency",
                    "caprivi","2001 special operations",
                    "operation juniper shield",
                    "san rebellion","vaalgras",
                    "monrovia"],
    "Americas":    ["america","american","colombia","colombian","mexico",
                    "mexican","peru","peruvian","bolivia","bolivian","panama",
                    "cuba","cuban","dominican","haiti","haitian",
                    "central america","nicaragu","guatemal","hondur",
                    "el salvador","salvadoran","venezuela","venezuelan",
                    "chile","chilean","argentin","brazil","brazilian",
                    "ecuador","ecuadori","paraguayan","paraguay","uruguay",
                    "falkland","malvinas","farc","contra","zapatist",
                    "canad","puerto ric","jamaica",
                    # Added: Latin American revolts, Caribbean, specific conflicts
                    "costa rica","grenada","trinidad",
                    "magonista","contestado","tenente",
                    "cristero","escobar rebellion","de la huerta",
                    "vaccine revolt","revolução","são paulo revolt",
                    "juazeiro","carupanazo","porteñazo",
                    "araguaia","guerrilha","machurucuto",
                    "rupununi","football war","kingston unrest",
                    "chiapas","cenepa","coto war",
                    "chaco war","manhattan rebellion",
                    "crazy snake","posey war","guna revolution",
                    "escambray","bay of pigs",
                    "la violencia","la matanza",
                    "negro rebellion","dirty war",
                    "catatumbo","confederalist rebellion",
                    "norte grande","revolution of 1930",
                    "calderonista","revolución libertadora",
                    "bluff war",
                    # Added round 2
                    "copacabana fort","estrada's rebellion",
                    "integralist","teoponte","ñancahuazú",
                    "united states occupation of veracruz",
                    "la revolución del 50","apra coup",
                    "palace rebellion","operation traíra"],
    "Pacific":     ["pacific","papua","samoa","fiji","hawaii","solomon islands",
                    "new zealand","australia","australian","timor","bougainville",
                    "oceani","mariana","midway","guadalcanal","iwo jima",
                    "okinawa",
                    # Added
                    "sokehs","coconut war","emu war","kanak",
                    "viqueque"],
    "Global":      ["world war","cold war","global","war on terror",
                    # Added
                    "war against the islamic state","gallipoli",
                    "six-day war","yom kippur","suez crisis"],
}
